services:
  database:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'video_upload'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'TEST123'
      MYSQL_ROOT_PASSWORD: 'rootPassword'
    volumes:
      - video_upload:/var/lib/platform_data

volumes:
  video_upload:
